-- ---------------------------------------------------------------------------
-- 0011 — El directorio se llama directorio, también adentro de la base
-- ---------------------------------------------------------------------------
-- La palabra que se usaba antes la había inventado la línea de comandos y nadie
-- la había aprobado. Al Desarrollador le resultó desagradable, con razón: dejaba
-- al Asistente como algo puesto en exhibición. El 24 de agosto de 2026 pidió
-- cambiarla, y después pidió que no quedara escrita en ningún archivo, porque
-- mientras esté escrita en alguno vuelve a aparecer sola. El registro de lo que
-- decía cada archivo antes está en el historial de Git, que es donde
-- corresponde y donde no se pisa por accidente.
--
-- El nombre bueno ya estaba escrito y no hubo que inventar nada: `docs/GLOSARIO.md`
-- dice que `directorio` nombra una pantalla, la pantalla ya se llamaba
-- `directorio.html`, la ficha ya se llamaba `perfil.html`, y la casilla del
-- consentimiento ya se llamaba `perfil_publicado`. Va sin adjetivo: directorio
-- hay uno solo y se ve sin sesión, así que «público» no distinguía nada.
--
-- Esta migración cambia únicamente lo que está guardado **adentro** de la base y
-- se lee desde afuera. No cambia ni una fila, ni una columna, ni un permiso.
--
-- **Sobre la política de `tenants`.** Cuando esta migración corrió en el
-- servidor traía además un `alter policy ... rename to "Directorio de
-- Prestadoras"`, porque 0002 la había creado con el nombre viejo. Ese renombre
-- ya se hizo y no se puede hacer dos veces. Y en una base levantada de cero hoy
-- tampoco hace falta, porque 0002 ya la crea con el nombre bueno. Por eso acá no
-- quedó: dejarlo haría fallar toda base nueva al no encontrar el nombre viejo.
-- Los dos caminos terminan igual, con la política llamándose «Directorio de
-- Prestadoras», que es lo único que importa.
-- ---------------------------------------------------------------------------

-- --- El comentario de la vista pública -------------------------------------
-- Lo escribió 0002 y lo reescribió 0007. Es la advertencia que lee quien vaya a
-- agregarle una columna, así que importa que se entienda.
comment on view public.caregivers_publicos is
  'Directorio de Asistentes. Dos condiciones, y las dos hacen falta: la Prestadora validó el legajo, y la persona marcó perfil_publicado. Nunca agregar acá una columna con datos personales: ni documento, ni teléfono, ni correo, ni domicilio, ni los caminos del depósito privado. El Desarrollador decidió el 24 de agosto de 2026 que este directorio se ve sin iniciar sesión, así que todo lo que se agregue acá queda a la vista de cualquiera.';
